[package]
name = "awala-vpn-shield"
version = "0.1.0"
edition = "2021"
authors = [ "Relaycorp <https://relaycorp.tech>" ]
description = "Awala VPN Gateway Shield"
repository = "https://github.com/AwalaApp/vpn-shield"
license-file = "LICENSE"
publish = false

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version="0.4.2", features=['http'] }
worker-macros = { version="0.4.2", features=['http'] }
console_error_panic_hook = { version = "0.1.1" }
http = "1.1"

# Work around https://github.com/cloudflare/workers-rs/issues/668
[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
